apiVersion: v1
kind: Pod
metadata:
  name: pod-1
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: cache
      mountPath: /cache
  - name: busybox
    image: busybox
    command: ["/bin/sh", "-c", "sleep 60000s"]
    volumeMounts:
    - name: cache
      mountPath: /wokao
  volumes:
  - name: cache
    emptyDir: {}
